demonstrator:
  name: grouped
  param:
    _target_: airbot_data_collection.demonstrate.demonstrators.grouped.GroupedDemonstrator
    auto_control:
      groups: []
    components:
      groups:
      - /
      names:
      - mmk
      params:
      - {}
      paths:
      - airbot_mmk
      roles:
      - o
  path: ''
dataset:
  directory: airbot_mmk
managers:
  names:
  - self_manager
  - keyboard
  params:
  - _target_: airbot_data_collection.managers.basis.SelfManager
  - _target_: airbot_data_collection.managers.keyboard.KeyboardCallbackManager
  paths:
  - ''
  - ''
sample_limit:
  size: 1000
  start_round: -1
sampler:
  name: airbot_mcap_sampler
  param:
    _target_: airbot_data_collection.airbot.samplers.mcap_sampler.AIRBOTMcapDataSampler
    task_info:
      object:
      - wooden_blocks
      - bowl
      operator: Anonymous
      scene: desktop
      skill:
      - pick
      - place
      station: mmk-MK11QWZ025170023
      subtasks:
      - description: pick the wooden blocks from the bowl with the gripper
        description_zh: "\u7528\u5939\u722A\u4ECE\u7897\u4E2D\u62FE\u53D6\u6728\u5236\
          \u79EF\u6728"
        skill: pick
      task_description: do some thing
      task_id: '135'
      task_name: anonymous task
    upload:
      enabled: false
      endpoint: 192.168.215.80
      password: '123456'
      username: admin
  path: ''
update_rate: 15
visualizers:
  names:
  - opencv
  params:
    - _target_: airbot_data_collection.airbot.visualizers.opencv.AIRBOTOpenCVVisualizer
      rate: 30
      concurrent_mode: process
  paths:
  - ''
