
stages:
  - test
  - build
  - shipping
  - release

style-test:
  stage: test
  tags:
    - linux/x86_64
  image: registry.qiuzhi.tech/library/pre-commit:1.0
  variables:
    PIP_INDEX_URL: "https://pypi.tuna.tsinghua.edu.cn/simple"
    PRE_COMMIT_HOME: "${CI_PROJECT_DIR}/.cache/pre-commit"
    HTTP_PROXY: ${PROXY_URL}
    http_proxy: ${PROXY_URL}
    HTTPS_PROXY: ${PROXY_URL}
    https_proxy: ${PROXY_URL}
    ALL_PROXY: ${PROXY_URL}
    all_proxy: ${PROXY_URL}
    NO_PROXY: ${NO_PROXY_URL}
    no_proxy: ${NO_PROXY_URL}
  cache:
    key: pre-commit
    paths:
      - .cache/pre-commit
  before_script:
    - pre-commit install
  script:
    - pre-commit run --all-files
