# _target_: airbot_data_collection.airbot.sensors.cameras.realsense.RealSense
_target_: airbot_data_collection.airbot.sensors.cameras.realsense.RealSenseConcurrent
camera_index: null
fps: 30
width: 640
height: 480
force_hardware_reset: true
color_mode: bgr
enable_depth: false
align_depth: false
