demonstrator:
  name: grouped
  param:
    _target_: airbot_data_collection.demonstrate.demonstrators.grouped.GroupedDemonstrator
    auto_control:
      # groups: []
      rates: [100]
      modes: [process]
    components:
      groups:
        - left
        - left
        - right
        - right
        - /
        - /
        - /
      names:
        - lead
        - follow
        - lead
        - follow
        - env_camera
        - left_camera
        - right_camera
      params:
        - port: 50050
        - port: 50051
        - port: 50052
        - port: 50053
        - camera_index: null
        - camera_index: null
        - camera_index: null
      paths:
        - airbot_play_mock
        - airbot_play_mock
        - airbot_play_mock
        - airbot_play_mock
        - mock_camera
        - mock_camera
        - mock_camera
      roles:
        - l
        - f
        - l
        - f
        - o
        - o
        - o
  path: ""
dataset:
  directory: arm1-001
managers:
  names:
    - self_manager
    - keyboard
  params:
    - _target_: airbot_data_collection.managers.basis.SelfManager
    - _target_: airbot_data_collection.managers.keyboard.KeyboardCallbackManager
  paths:
    - ""
    - ""
sample_limit:
  size: 1000
  start_round: -1
concurrent_save: none
update_rate: 20
sampler:
  name: airbot_mcap_sampler
  param:
    _target_: airbot_data_collection.airbot.samplers.mcap_sampler.AIRBOTMcapDataSampler
    task_info:
      operator: Anonymous
      station: ptk-001
      task_name: anonymous task
      task_description: do some thing
      task_id: "135"
      skill:
        - pick
        - place
      object:
        - wooden_blocks
        - bowl
      scene: desktop
      subtasks:
        - skill: pick
          description: pick the wooden blocks from the bowl with the gripper
          description_zh: 用夹爪从碗中拾取木制积木
    upload:
      enabled: false
      endpoint: 192.168.215.80
      username: admin
      password: "123456"
  path: ""
visualizers:
  names:
    - opencv
  params:
    - _target_: airbot_data_collection.airbot.visualizers.opencv.AIRBOTOpenCVVisualizer
      rate: 30
      concurrent_mode: process
  paths:
    - ""
