sampler:
  name: airbot_bson_sampler
  path: ""
  param:
    _target_: airbot_data_collection.airbot.samplers.bson_sampler.AIRBOTDataSampler

visualizers:
  names: [opencv]
  paths: ["", ""]
  params:
    - _target_: airbot_data_collection.airbot.visualizers.opencv.AIRBOTOpenCVVisualizer
      width: 640
      height: 480

managers:
  names: [self_manager, joycontrol]
  paths: ["", ""]
  params:
    - _target_: airbot_data_collection.managers.basis.SelfManager
    - _target_: airbot_data_collection.managers.joycontrol.JoyCallbackManager
